Dev
addod19/youtube-clone pull request #1
Opened 2019-06-06 22:20 UTC by addod19

code review request

2019-06-06 22:54 UTC, bellom requested changes
Hi, @addod19 
<h2>Good first attempt. Needs a bit more of work</h2>
Hello! 👋🏼 You are on the right path, the project looks good. well done working alone. 
Just few things to do;
<li>update the README file</li>
example below; 

![image](https://user-images.githubusercontent.com/31897434/59054922-a06fef00-888c-11e9-9050-c971b7b03977.png)

<li>worked on the nav bar text input and search button</li>
example below; 

![image](https://user-images.githubusercontent.com/31897434/59071030-ee98e880-88b4-11e9-9b03-f69f186a56e6.png)

<li>run your code on (https://validator.w3.org) and fix the errors.</li><br>

Submit a new code review request. Thanks!

Tips:
For every HTML/CSS projects please check your files with the W3 Validator and the CSS Linter

2019-06-06 23:07 UTC, bellom requested changes

2019-06-06 23:07 UTC, bellom commented on assets/style.css
> +    position: absolute;
Please try your best to have DRY(don't repeat yourself) code.
line 20, 28, 36, 42, 49, 56, 62, 69 could be written in one liner.
example; 
```
nav, a, span {
  position: absolute;
}
```

2019-06-07 19:21 UTC, bellom requested changes
Hi, @addod19 
**_Great work, i can see you now have DRY code, Awesome!! :smile:_**
**_For some reason you didn't work completely on the previous PR corrections._**
Kindly work on the following:
<li>worked on the nav bar text input and search button, 
the search button should be at the end (rightmost part) of the search bar.</li>
example below; 

![image](https://user-images.githubusercontent.com/31897434/59071030-ee98e880-88b4-11e9-9b03-f69f186a56e6.png)

<li>run your code on (https://validator.w3.org) and fix the errors.</li><br>
[i ran your code on w3 validator, you have a lot of errors you need to fix] 

**Free free to message me on slack if you need help.**

Submit a new code review request. Thanks!

Tips:
For every HTML/CSS projects please check your files with the W3 Validator and the CSS Linter

2019-06-08 13:04 UTC, bellom approved these changes
Hi @addod19 
<h2>Great work fixing all the validator errors :+1: </h2>
<h4>Congratulations</h4> you can go ahead and merge to master.

2019-06-08 13:26 UTC, merged

2019-06-08 13:27 UTC, addod19 commented
project one: YouTube Clone Completed